language: node_js
node_js:
  - "8"
  - "10"
  - "11"
  - "node"

script:
  - npm run lint
  - npm run spa-generate

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: ucrcyber.org  
